name: nightly-scrape
on:
  schedule:
    - cron: "0 18 * * *"   # daily at 18:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (discover+details)
        run: |
          python -m src.main --phase all --portals lamudi_cebu
      - name: Dry-run discovery (no DB writes)
        env:
          DRYRUN_MAX_PAGES: "2"
          DRYRUN_MODE: "playwright"     # or leave unset if your portals config is solid
          DRYRUN_RATE_DELAY: "0.5"
        run: |
          python -m pip install -r requirements.txt
          python scripts/dry_run_discovery.py  

      - name: Load latest JSONL to Postgres
        run: |
          LATEST_JSONL=$(ls -1 scraper_output/run_*/staged/lamudi_cebu_listings.jsonl | tail -n1)
          python -m src.etl.load_to_postgres --input "$LATEST_JSONL" --table listings
