name: Nightly Lamudi Cebu Scrape

on:
  schedule:
    # GitHub cron runs in UTC. 3:00 AM Manila (UTC+8) == 19:00 UTC previous day
    - cron: "0 19 * * *"
  workflow_dispatch:
    inputs:
      max_listings:
        description: "Hard cap listings (0 = all on pages visited)"
        required: false
        default: "30"
      max_pages:
        description: "Pagination cap"
        required: false
        default: "1"
      rate_limit_delay:
        description: "Seconds between requests"
        required: false
        default: "1.2"
      scraping_mode:
        description: "requests | playwright"
        required: false
        default: "playwright"
env:
  TZ: Asia/Manila
  PYTHONUNBUFFERED: "1"
  # Fallbacks; workflow_dispatch can override these
  SCRAPING_MODE: ${{ github.event.inputs.scraping_mode || 'playwright' }}
  RATE_LIMIT_DELAY: ${{ github.event.inputs.rate_limit_delay || '1.2' }}
  MAX_PAGES: ${{ github.event.inputs.max_pages || '1' }}
  MAX_LISTINGS: ${{ github.event.inputs.max_listings || '30' }}

  # Required by your app
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Initial test
        run: echo "Foundation is solid."
