name: Nightly Lamudi Cebu Scrape

on:
  workflow_dispatch:
  schedule:
    # 3:00 AM Asia/Manila = 19:00 UTC the previous day
    - cron: "0 19 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      # Scraper knobs for CI
      SCRAPING_MODE: playwright
      RATE_LIMIT_DELAY: "1.0"
      MAX_PAGES: "1"
      MAX_LISTINGS: "0"        # set "0" to remove the hard cap
      LOG_LEVEL: INFO
      PORTALS_CONFIG: ./config/portals.json

      # DB (pulled from repo/environment secrets)
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure Playwright + Chromium are installed for headless scraping
          python -c "import importlib, sys; sys.exit(0 if importlib.util.find_spec('playwright') else 1)" \
            && python -m playwright install --with-deps chromium || true

      - name: Install Playwright browsers
        run: |
            python -m playwright install --with-deps chromium    

      - name: Discovery (lamudi_cebu)
        run: |
          python -m src.runner.run_discovery --portal lamudi_cebu

      - name: Capture run dir
        id: disco
        shell: bash
        run: |
          set -e
          latest=$(ls -1d scraper_output/run_* | tail -n1)
          echo "RUN_DIR=$latest" >> "$GITHUB_OUTPUT"
          echo "Captured RUN_DIR: $latest"

      - name: Details (lamudi_cebu)
        run: |
          python -m src.runner.run_details --portal lamudi_cebu --run-dir "${{ steps.disco.outputs.RUN_DIR }}"

      - name: Publish to Supabase
        run: |
          python -m src.runner.write_portal_dump_to_supabase --portal lamudi_cebu --run-dir "${{ steps.disco.outputs.RUN_DIR }}"

      # Optional: quick sanity log (doesn't fail the job if it can't query)
      - name: Sanity echo staged head
        continue-on-error: true
        run: |
          head -n 5 "${{ steps.disco.outputs.RUN_DIR }}/staged/lamudi_cebu_listings.jsonl" || true
