name: nightly-scrape

on:
  schedule:
    - cron: "0 18 * * *"     # daily 18:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ vars.ENV }}
      MAX_PAGES: ${{ vars.MAX_PAGES }}
      RATE_LIMIT_DELAY: ${{ vars.RATE_LIMIT_DELAY }}
      SCRAPING_MODE: ${{ vars.SCRAPING_MODE }}
      PORTALS_CONFIG: ${{ vars.PORTALS_CONFIG }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ Correct way for CI: install Chromium + system deps
      - name: Install Playwright (browsers + deps)
        run: |
          python -m playwright install --with-deps chromium

      - name: Validate required secrets
        run: |
          test -n "$SUPABASE_URL" || (echo "Missing SUPABASE_URL" && exit 1)
          test -n "$SUPABASE_SERVICE_ROLE_KEY" || (echo "Missing SUPABASE_SERVICE_ROLE_KEY" && exit 1)

      - name: Run discovery
        run: python -m src.scripts.run_discovery --portal lamudi_cebu

      - name: Run details
        run: |
          RUN_DIR=$(ls -1d scraper_output/run_* | tail -n1)
          echo "Using run dir: $RUN_DIR"
          python -m src.scripts.run_details --portal lamudi_cebu --run-dir "$RUN_DIR"

      - name: Write portal dump to Supabase
        run: |
          RUN_DIR=$(ls -1d scraper_output/run_* | tail -n1)
          python -m src.scripts.write_portal_dump_to_supabase --portal lamudi_cebu --run-dir "$RUN_DIR"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lamudi_cebu_jsonl
          path: |
            scraper_output/run_*/staged/lamudi_cebu_urls.jsonl
            scraper_output/run_*/staged/lamudi_cebu_listings.jsonl
          if-no-files-found: ignore
